# Generated by Django 4.2.16 on 2024-11-22 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VocabList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_name", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VocabWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hirgana", models.TextField()),
                ("kanji", models.TextField(blank=True)),
                ("english_meaning", models.TextField()),
                ("lesson_num", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="WrongList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vocabulary_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.vocablist",
                    ),
                ),
                ("vocabulary_words", models.ManyToManyField(to="project.vocabword")),
            ],
        ),
        migrations.AddField(
            model_name="vocablist",
            name="vocabulary_words",
            field=models.ManyToManyField(to="project.vocabword"),
        ),
    ]
