# Generated by Django 4.2.16 on 2024-12-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_alter_vocablist_list_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="vocablist", unique_together=set(),),
        migrations.AddConstraint(
            model_name="vocablist",
            constraint=models.UniqueConstraint(
                fields=("list_name", "user"), name="unique_list_name"
            ),
        ),
    ]
