# Generated by Django 4.2.16 on 2024-12-11 01:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0006_alter_vocablist_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="vocablist", name="unique_list_name",),
        migrations.AlterUniqueTogether(
            name="vocablist", unique_together={("list_name", "user")},
        ),
    ]
